"ONOS":
  "environment":
    "OC1": "10.20.0.7"
    "OC2": "10.20.0.7"
    "OC3": "10.20.0.7"
    "OCN": "10.20.0.4"
    "OCN2": "10.20.0.5"
    "OCT": "10.20.0.1"
    "installer_master": "10.20.0.2"
    "installer_master_password": "r00tme"
    "installer_master_username": "root"
  "general":
    "onosbench_password": "root"
    "onosbench_username": "root"
    "onoscli_password": "root"
    "onoscli_username": "root"
    "runtimeout": !!int "300"
"energy_recorder":
  "api_password": ""
  "api_url": "http://opnfv.fr:8888/resources"
  "api_user": ""
"example":
  "flavor": "m1.small"
  "image_name": "functest-example-vm"
  "private_net_name": "example-net"
  "private_subnet_cidr": "192.168.170.0/24"
  "private_subnet_name": "example-subnet"
  "router_name": "example-router"
  "sg_desc": "Example Security group"
  "sg_name": "example-sg"
  "vm_name": "example-vm"
"general":
  "dir":
    "dir_repo_rally": "/home/opnfv/repos/rally"
    "dir_repo_releng": "/home/opnfv/repos/releng"
    "functest": "/home/opnfv/functest"
    "functest_conf": "/home/opnfv/functest/conf"
    "functest_data": "/home/opnfv/functest/data"
    "functest_images": "/home/opnfv/functest/images"
    "home": "/home/opnfv"
    "ims_data": "/home/opnfv/functest/data/ims/"
    "rally_inst": "/root/.rally"
    "repo_barometer": "/home/opnfv/repos/barometer"
    "repo_copper": "/home/opnfv/repos/copper"
    "repo_doctor": "/home/opnfv/repos/doctor"
    "repo_domino": "/home/opnfv/repos/domino"
    "repo_fds": "/home/opnfv/repos/fds"
    "repo_netready": "/home/opnfv/repos/netready"
    "repo_onos": "/home/opnfv/repos/onos"
    "repo_securityscan": "/home/opnfv/repos/securityscanning"
    "repo_tempest": "/src/tempest"
    "repo_vims_test": "/home/opnfv/repos/vnfs/vims-test"
    "repo_vrouter": "/home/opnfv/repos/vnfs/vrouter"
    "repos": "/home/opnfv/repos"
    "results": "/home/opnfv/functest/results"
  "flavor_extra_specs":
    "hw:mem_page_size": "large"
  "image_properties":
    "hw_mem_page_size": "large"
  "openstack":
    "creds": "/home/opnfv/functest/conf/openstack.creds"
    "flavor_disk": !!int "1"
    "flavor_name": "opnfv_flavor"
    "flavor_name_alt": "opnfv_flavor_1"
    "flavor_ram": !!int "512"
    "flavor_vcpus": !!int "1"
    "image_disk_format": "qcow2"
    "image_file_name": "cirros-0.3.5-x86_64-disk.img"
    "image_name": "Cirros-0.3.5"
    "image_name_alt": "Cirros-0.3.5-1"
    "image_password": "cubswin:)"
    "image_url": "http://download.cirros-cloud.net/0.3.5/cirros-0.3.5-x86_64-disk.img"
    "image_user": "cirros"
    "image_username": "cirros"
    "neutron_private_net_name": "functest-net"
    "neutron_private_subnet_cidr": "192.168.120.0/24"
    "neutron_private_subnet_end": "192.168.120.254"
    "neutron_private_subnet_gateway": "192.168.120.254"
    "neutron_private_subnet_name": "functest-subnet"
    "neutron_private_subnet_start": "192.168.120.2"
    "neutron_router_name": "functest-router"
    "snapshot_file": "/home/opnfv/functest/conf/openstack_snapshot.yaml"
"multisite":
  "compass":
    "installer_password": "root"
    "installer_username": "root"
    "multisite_controller_ip": "10.1.0.50"
  "fuel":
    "installer_password": "r00tme"
    "installer_username": "root"
"odl_sfc":
  "image_base_url": "http://artifacts.opnfv.org/sfc/images"
  "image_file_name": "sfc_nsh_danube.qcow2"
  "image_format": "qcow2"
  "image_name": "sfc_nsh_danube"
"onos_sfc":
  "image_base_url": "http://artifacts.opnfv.org/sfc/demo"
  "image_file_name": "firewall_block_image.img"
  "image_name": "TestSfcVm"
"promise":
  "flavor_disk": !!int "0"
  "flavor_name": "promise-flavor"
  "flavor_ram": !!int "128"
  "flavor_vcpus": !!int "1"
  "image_name": "promise-img"
  "network_name": "promise-net"
  "router_name": "promise-router"
  "subnet_cidr": "192.168.121.0/24"
  "subnet_name": "promise-subnet"
  "tenant_description": "promise Functionality Testing"
  "tenant_name": "promise"
  "user_name": "promiser"
  "user_pwd": "test"
"rally":
  "deployment_name": "opnfv-rally"
  "network_name": "rally-net"
  "router_name": "rally-router"
  "subnet_cidr": "192.168.140.0/24"
  "subnet_name": "rally-subnet"
"results":
  "test_db_url": "http://testresults.opnfv.org/test/api/v1/results"
"snaps":
  "images":
    "centos":
      "disk_file": "/home/opnfv/functest/images/CentOS-7-x86_64-GenericCloud.qcow2"
    "cirros":
      "disk_file": "/home/opnfv/functest/images/cirros-0.3.5-x86_64-disk.img"
    "glance_tests":
      "disk_file": "/home/opnfv/functest/images/cirros-0.3.5-x86_64-disk.img"
    "ubuntu":
      "disk_file": "/home/opnfv/functest/images/ubuntu-14.04-server-cloudimg-amd64-disk1.img"
  "use_floating_ips": !!bool "true"
  "use_keystone": !!bool "true"
"tempest":
  "deployment_name": "opnfv-tempest"
  "identity":
    "tenant_description": "Tenant for Tempest test suite"
    "tenant_name": "tempest"
    "user_name": "tempest"
    "user_password": "Tempest123!"
  "object_storage":
    "operator_role": "SwiftOperator"
  "private_net_name": "tempest-net"
  "private_subnet_cidr": "192.168.150.0/24"
  "private_subnet_name": "tempest-subnet"
  "router_name": "tempest-router"
  "use_custom_flavors": !!bool "true"
  "use_custom_images": !!bool "true"
  "validation":
    "ssh_timeout": !!int "130"
  "volume_device_name": "vdc"
"vnf":
  "aaa":
    "tenant_description": "Freeradius server"
    "tenant_images": {}
    "tenant_name": "aaa"
  "cloudify_ims":
    "config": "cloudify_ims.yaml"
    "tenant_description": "vIMS"
    "tenant_name": "cloudify_ims"
  "juju_epc":
    "config": "juju_epc.yaml"
    "tenant_description": "OAI EPC deployed with Juju"
    "tenant_name": "debayanProject"
    "private_net_name": "abot-net"
    "private_subnet_cidr": "172.16.0.0/24"
    "private_subnet_name": "abot-subnet"
    "external_router": "abot-router"
    "external_network_name": "ext-net"
    "dns_nameserver": ['8.8.8.8']
  "opera_ims":
    "tenant_description": "ims deployed with open-o"
    "tenant_name": "opera_ims"
  "orchestra_ims":
    "config": "orchestra_ims.yaml"
    "tenant_description": "ims deployed with openbaton"
    "tenant_name": "orchestra_ims"
"vping":
  "cleanup_objects": !!bool "true"
  "image_name": "functest-vping"
  "keypair_name": "vPing-keypair"
  "keypair_priv_file": "/tmp/vPing-keypair"
  "keypair_pub_file": "/tmp/vPing-keypair.pub"
  "ping_timeout": !!int "200"
  "private_net_name": "vping-net"
  "private_subnet_cidr": "192.168.130.0/24"
  "private_subnet_name": "vping-subnet"
  "router_name": "vping-router"
  "sg_desc": "Security group for vPing test case"
  "sg_name": "vPing-sg"
  "unique_names": !!bool "true"
  "vm_boot_timeout": !!int "180"
  "vm_delete_timeout": !!int "100"
  "vm_flavor": "m1.tiny"
  "vm_name_1": "opnfv-vping-1"
  "vm_name_2": "opnfv-vping-2"
  "vm_ssh_connect_timeout": !!int "60"
